---
title: "Model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description

The model has two resources, two viruses, and a single plant host. The plant-resource relationship is based on models of phytoplankton (Klausmeier et al. 2004) and terrestrial plants (Grace and Tilman 2003). Pathogens were added following models of plant-virus-resource relationships (Fuhrman et al. 2011, Béchette et al. 2013, Gerla et al. 2013, Pell et al. 2019). The plant takes up resources from the environment and integrates them into its tissues. The two viruses and the host then compete for resource-derived molecules.        

\begin{equation}
\begin{gathered}
\frac{dR_{1}}{dt} = s_{1} - \frac{u_{1}R_{1}H}{R_{1}+c_{1}}
\\
\frac{dR_{2}}{dt} = s_{2} - \frac{u_{2}R_{2}H}{R_{2}+c_{2}}
\\
\frac{dQ_{1}}{dt} = \frac{u_{1}R_{1}}{R_{1}+c_{1}} - \mu_{H}min\left(1-\frac{q_{H,1}}{Q_{1}}, 1-\frac{q_{H,2}}{Q_{2}}\right)Q_{1} - \mu_{1}k_{1,1}min\left(1-\frac{q_{1,1}}{Q_{1}}, 1-\frac{q_{1,2}}{Q_{2}}\right)V_{1} - \mu_{2}k_{2,1}min\left(1-\frac{q_{2,1}}{Q_{1}}, 1-\frac{q_{2,2}}{Q_{2}}\right)V_{2}
\\
\frac{dQ_{2}}{dt} = \frac{u_{2}R_{2}}{R_{2}+c_{2}} - \mu_{H}min\left(1-\frac{q_{H,1}}{Q_{1}}, 1-\frac{q_{H,2}}{Q_{2}}\right)Q_{2} - \mu_{1}k_{1,2}min\left(1-\frac{q_{1,1}}{Q_{1}}, 1-\frac{q_{1,2}}{Q_{2}}\right)V_{1} - \mu_{2}k_{2,2}min\left(1-\frac{q_{2,1}}{Q_{1}}, 1-\frac{q_{2,2}}{Q_{2}}\right)V_{2}
\\
\frac{dH}{dt} = \mu_{H}min\left(1-\frac{q_{H,1}}{Q_{1}}, 1-\frac{q_{H,2}}{Q_{2}}\right)H - m_{H}H
\\
\frac{dV_{1}}{dt} = \mu_{1}min\left(1-\frac{q_{1,1}}{Q_{1}}, 1-\frac{q_{1,2}}{Q_{2}}\right)V_{1} - m_{1}V_{1}
\\
\frac{dV_{2}}{dt} = \mu_{2}min\left(1-\frac{q_{2,1}}{Q_{1}}, 1-\frac{q_{2,2}}{Q_{2}}\right)V_{2} - m_{2}V_{2}
\end{gathered}
\end{equation}

We assume that resource $j$ in the environment ($R_{j}$) is supplied at a constant rate $s_{j}$ and taken up by the plant host $H$ with a Michaelis-Menten functional form. We will refer to this uptake function $\frac{u_{j}R_{j}}{R_{j}+c_{j}}$ as $f(R_{j})$. Larger hosts take up more resource. $V_{i}$ represents the concentration of virions of species $i$. The concentration of resource $j$ within the host $Q_{j}$ is diluted by host growth and reduced by virus $i$ replication. We invoke Liebig's law of the minimum with minimum functions that make host growth and virus replication depend on the most limiting resources based on their respective resource requirements (von Liebig 1840, Droop 1974, Leon and Tumpson 1975). The concentration of resource $j$ at which host growth ceases is $q_{H,j}$ and the concentration of resource $j$ at which replication of virus $i$ ceases is $q_{i,j}$. With abundant resource, the host and virus grow at their respective maximum rates $\mu$. The proportion of virus growth that consumes resource $j$ is $k_{i,j}$. Host biomass is lost (e.g., senescing) at rate $m_{H}$ and virions are removed (e.g., by the immune system) at rate $m_{i}$. 

Because viruses require live cells in which to replicate, we assume $q_{i,j} > q_{H,j}$ for each virus species $i$ and resource $j$. [List other assumptions and constraints here]    

## Equilibrium

Following Klausmeier et al. (2004), we can solve for the equilibrium states of the host and resources in the absence of infection.  

At equilibrium, one resource $Q_{lim}$ limits growth. To find the equilibrium concentration of $Q_{lim}$ ($\hat{Q}_{lim}$), we set $dH/dt = 0$,  
\begin{equation}
\begin{gathered}
\mu_{H}\left(1-\frac{q_{H,lim}}{Q_{lim}}\right)H - m_{H}H = 0
\\
\mu_{H}\left(1-\frac{q_{H,lim}}{Q_{lim}}\right) = m_{H}
\\
1 - \frac{q_{H,lim}}{Q_{lim}} = \frac{m_{H}}{\mu_{H}}
\\
1 - \frac{m_{H}}{\mu_{H}} = \frac{q_{H,lim}}{Q_{lim}}
\\
\hat{Q}_{lim} = q_{H,lim}\left(\frac{\mu_{H}}{\mu_{H} - m_{H}}\right)
\end{gathered}
\end{equation}
This result suggests that the equilibrium concentration of the resource that most limits host growth will be higher when the host is less tolerant of resource limitation (i.e., $q_{H,lim}$ is high) or when the host's mortality rate is high. A lower net growth rate $\mu_{H}-m_{H}$ will also increase $\hat{Q}_{lim}$.  

To find the equilibrium concentration of resource in the environment when the host's growth is equal to mortality, we set $dQ_{lim}/dt = 0$,
\begin{equation}
\begin{gathered}
\frac{u_{lim}R_{lim}}{R_{lim}+c_{lim}} - \mu_{H}\left(1-\frac{q_{H,lim}}{\hat{Q}_{lim}}\right)\hat{Q}_{lim} = 0
\\
\frac{R_{lim}}{R_{lim}+c_{lim}} = \frac{\mu_{H}(\hat{Q}_{lim}-q_{H,lim})}{u_{lim}}
\\
\frac{u_{lim}}{\mu_{H}(\hat{Q}_{lim}-q_{H,lim})} = 1 + \frac{c_{lim}}{R_{lim}}
\\
\frac{u_{lim} - \mu_{H}(\hat{Q}_{lim}-q_{H,lim})}{\mu_{H}(\hat{Q}_{lim}-q_{H,lim})} = \frac{c_{lim}}{R_{lim}}
\\
\hat{R}_{lim} = \frac{c_{lim}\mu_{H}(\hat{Q}_{lim}-q_{H,lim})}{u_{lim} - \mu_{H}(\hat{Q}_{lim}-q_{H,lim})}
\\
\hat{Q}_{lim}-q_{H,lim} = \frac{q_{H,lim}m_{H}}{\mu_{H}-m_{H}}
\\
\hat{R}_{lim} = R^*_{lim} = \frac{q_{H,lim}m_{H}\mu_{H}c_{lim}}{u_{lim}(\mu_{H} - m_{H}) - q_{H,lim}m_{H}\mu_{H}}
\end{gathered}
\end{equation}
Similar to the result for $\hat{Q}_{lim}$, this result suggests that the equilibrium resource in the environment will be larger when the host is less tolerant of resource limitation or has a low net growth rate. $\hat{R}_{lim}$ will also be larger when  when the host's maximum uptake rate $u_{lim}$ is slow and when host resource uptake is less sensitive to resource availability (large $c_{lim}$). These characteristics would also make the host a poorer resource competitor with other hosts (i.e., larger $R^*_{lim}$).  

To find the equilibrium biomass of the host, we set $dR_{lim}/dt = 0$ and use the equations for $dQ_{lim}/dt$ and $\hat{Q}_{lim}$,
\begin{equation}
\begin{gathered}
\hat{H} = \frac{s_{lim}}{f_{lim}(\hat{R}_{lim})}
\\
f_{lim}(\hat{R}_{lim}) = \mu_{H}\left(1 - \frac{q_{H,lim}}{\hat{Q}_{lim}}\right)\hat{Q}_{lim}
\\
\hat{H} = \frac{s_{lim}}{\mu_{H}(\hat{Q}_{lim} - q_{H,lim})}
\\
\hat{H} = \frac{s_{lim}(\mu_{H} - m_{H})}{q_{H,lim}\mu_{H}m_{H}}
\end{gathered}
\end{equation}
This result suggests that a high supply rate, high tolerance of resource limitation (small $q_{H,lim}$), low mortality rate, and high net growth rate can increase host biomass.  

When we include one virus in the model, the equation for $\hat{Q}_{lim}$ is the same, but to specify that this is the resource most limiting to the host, we will refer to it as $\hat{Q}_{H,lim}$. If the host and virus are limited by different resources, the equilibrium concentration of the resource most limiting to virus $i$ is found by setting $dV_{i}/dt = 0$,
\begin{equation}
\hat{Q}_{i,lim} = q_{i,lim}\left(\frac{\mu_{i}}{\mu_{i} - m_{i}}\right)
\end{equation}
[start here: not sure if this is right. What is the mechanism that allows the virus to regulate this resource level. Is it accurate?]